project:
  type: website
  output-dir: docs

website:
  title: "Japan Typhoon Map"
  search: true
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    # logo: "./logo/qe labs logo - white bg.jpg"
    logo: "./logo/QE-Labs Logo - Copy.png"
    logo-alt: "Quantified Energy Labs (QE-Labs)"
    logo-href: https://www.linkedin.com/company/qe-labs/?originalSubdomain=sg

  sidebar:
    tilte: "Contents"
    style: "floating"

    search: true
    contents:
      - section: "Production"
        contents:
          - tidyup.qmd
          - plot.qmd
      - section: "Test"
        contents:
          - test.qmd
  page-footer:
    center: © 2024 &middot; [Quantified Energy Labs (QE-Labs)](https://www.linkedin.com/company/qe-labs/?originalSubdomain=sg)


format:
  html:
    code-block-bg: true
    code-block-border-left: true
    code-copy: true
    code-fold: true
    code-line-numbers: true
    code-overflow: wrap
    code-tools: true
    css: styles.css
    theme:
      light: cosmo
      dark: darkly
    toc: true
  ipynb: default

hightlight-style: gruvbox
