project:
  type: website

website:
  title: "Jp_typhoon_data_tidy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    tilte: "Contents"
    style: "floating"
    search: true
    contents:
      - section: "Production"
        contents:
          - tidyup.qmd
          - plot.qmd
      - section: "Test"
        contents:
          - test.qmd

format:
  html:
    code-block-bg: true
    code-block-border-left: true
    code-copy: true
    code-fold: true
    code-line-numbers: true
    code-overflow: wrap
    code-tools: true
    css: styles.css
    theme:
      light: cosmo
      dark: darkly
    toc: true
  ipynb: default
  pdf: default

hightlight-style: gruvbox
